ERROR   2022-08-22 17:24:52,157D:\work_code\pytest-auto-api2\logs\error-{now_time_day}.log:log_control.py:84 测试
ERROR   2022-08-23 09:20:18,082D:\work_code\pytest-auto-api2\logs\error-{now_time_day}.log:conftest.py:116 失败用例数: 0
ERROR   2022-08-23 09:30:18,527D:\work_code\pytest-auto-api2\logs\error-{now_time_day}.log:conftest.py:116 失败用例数: 0
